server.port=8080

# Значения пользователя для быстрого локального запуска.
gigachat.auth-key=MDE5YTUzODgtMWJhYy03NTA3LTlmMDgtODE0MzQyNTM5YmUwOjcxZmI4N2YzLWMwZTQtNDBhOC04MWY0LTJmMjcyOGNmNTk0ZQ==
gigachat.client-id=019a5388-1bac-7507-9f08-814342539be0
gigachat.client-secret=71fb87f3-c0e4-40a8-81f4-2f2728cf594e
gigachat.scope=GIGACHAT_API_PERS
gigachat.model=GigaChat
gigachat.base-url=https://gigachat.devices.sberbank.ru
